server.port=8081
spring.application.name=auth-service

# MySQL – auth database
spring.datasource.url=jdbc:mysql://localhost:3306/gympro_auth?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# JWT
jwt.secret=gympro_jwt_secret_key_for_hs256_algorithm_minimum_256_bits
jwt.expiration=3600000


#Connection 
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.virtual-host=/


spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.cache.connection.mode=CHANNEL
spring.rabbitmq.cache.channel.size=5

spring.rabbitmq.connection-timeout=60000
spring.rabbitmq.requested-heartbeat=60

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
